apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: delivery-service
spec:
  selector:
    app: deliveryservice
  ports:
    - protocol: "TCP"
      port: 9091 # The port that the service is running on in the cluster
      targetPort: 9091 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: deliveryservice
spec:
  selector:
    matchLabels:
      app: deliveryservice
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: deliveryservice
    spec:
      containers:
        - name: deliveryservice 
          image: docker.io/34shehan/delivery_service:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 9091 # The port that the container is running on in the cluster
