apiVersion: v1
kind: Secret
metadata:
  name: email-secret
data:
  SENDER_EMAIL: eWVhcjRyZXNlYXJjaHRlYW1zbGlpdEBnbWFpbC5jb20=
  SENDER_PASSWORD: eWVhcjRyZXNlYXJjaDE5OTg=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-deployment
  labels:
    app: emailservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: emailservice
          image: docker.io/nikaloFlamel/email-service:v1.0.0
          ports:
            - containerPort: 9040
          env:
            - name: SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: SENDER_EMAIL
            - name: SENDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: SENDER_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  type: LoadBalancer
  selector:
    app: emailservice
  ports:
    - protocol: TCP
      port: 9040
      targetPort: 9040
